# Simple workflow for deploying static content to GitHub Pages
name: Continuous Integration - Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 
    - name: Setup .NET 7
      uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8
      with:
        dotnet-version: 7.0.x
      
    # publishes Blazor project to the release-folder
    # uses  -p:GHPages=true comes from > dotnet add package PublishSPAforGitHubPages.Build
    - name: Publish BlazorApp
      run: dotnet publish src/BlazorApp/BlazorApp.csproj -c Release -o blazorapp -p:GHPages=true /p:AssemblyVersion=1.0.0.${{ github.run_number }} /p:Version=1.0.0.${{ github.run_number }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: blazorapp
        # Upload wwwroot only
        path: 'blazorapp/wwwroot/'

    - name: Publish BlazorApp-Api
      run: dotnet publish src/BlazorAppApi/BlazorAppApi.csproj -c Release -o blazorapp-api /p:AssemblyVersion=1.0.0.${{ github.run_number }} /p:Version=1.0.0.${{ github.run_number }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: blazorapp-api
        path: 'blazorapp-api'